### ISSUE TITLE
Show diff in addition to long before / after text snapshots

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/snap-shot-compare#6]
Right now just printing snapshot and actual long text is nice, but we need to show the diff too.
Otherwise what has changed between these two?

```
Error: Saved snapshot text
--------------

Started video recording: /foo/bar/.projects/e2e/cypress/videos/abc123.mp4

  (Tests Starting)


  1) fails
  ✓ should be able to log

  1 passing
  1 failing

  1)  fails:
     CypressError: Timed out retrying: Expected to find element: 'element_does_not_exist', but never found it.
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line




  (Tests Finished)

  - Tests:           2
  - Passes:          1
  - Failures:        1
  - Pending:         0
  - Duration:        10 seconds
  - Screenshots:     1
  - Video Recorded:  true
  - Cypress Version: 1.2.3


  (Screenshots)

  - /foo/bar/.projects/e2e/cypress/screenshots/fails.png (1280x720)


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /foo/bar/.projects/e2e/cypress/videos/abc123.mp4 (0 seconds)


  (All Done)


--------------
Current text
--------------

Started video recording: /foo/bar/.projects/e2e/cypress/videos/abc123.mp4

  (Tests Starting)


  1) fails
  ✓ should be able to log

  1 passing
  1 failing

  1)  fails:
     CypressError: Timed out retrying: Expected to find element: 'element_does_not_exist', but never found it.
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line
      at stack trace line




  (Tests Finished)

  - Tests:           2
  - Passes:          1
  - Failures:        1
  - Pending:         0
  - Duration:        10 seconds
  - Screenshots:     1
  - Video Recorded:  true
  - Cypress Version: 1.2.3


  (Screenshots)

  - /foo/bar/.projects/e2e/cypress/screenshots/fails.png (1280x720)


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /foo/bar/.projects/e2e/cypress/videos/abc123.mp4 (0 seconds)


  (All Done)


--------------

    at result.orElse.message (node_modules/snap-shot-core/src/file-system.js:134:11)
    at undefined.orElse (node_modules/folktale/result/result.js:187:14)
    at raiseIfDifferent (node_modules/snap-shot-core/src/file-system.js:130:10)
    at setOrCheckValue (node_modules/snap-shot-core/src/index.js:221:5)
    at snapShotCore (node_modules/snap-shot-core/src/index.js:233:12)
    at snapshot (node_modules/snap-shot-it/src/index.js:116:10)
    at ChildProcess.<anonymous> (test/support/helpers/e2e.coffee:212:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by bahmutov** [comment]
Version `2.6.0` has been published to NPM. The full release note can be found at [snap-shot-compare/releases/tag/v2.6.0](https://github.com/bahmutov/snap-shot-compare/releases/tag/v2.6.0).

**Tip:** safely upgrade dependency snap-shot-compare in your project using [next-update](https://github.com/bahmutov/next-update)
